tags = ["tagA", "tagB"]

[behaviours]

[behaviours.logging]
type = "logfile"
when = "always"

[behaviours.logging.settings]
directory = "/var/log"
filename = "gaze.log"
format = "human"

[behaviours.request]
type = "web"
when = "always"

[behaviours.request.settings]
url = "http://127.0.0.1:8080"
